### ISSUE TITLE
Drop LICENSE.GPL2

### ISSUE THREAD

**Issue by jbeich** [emersion/basu#33]
meson.build and SPDX headers point to LICENSE.**LGPL2.1**. 184eca5f89e3 and 1914a30c3beb removed `GPL-2.0` remains. Does anything else still need LICENSE.**GPL2**?

```
$ fgrep license meson.build
license : 'LGPLv2+',

$ rg -NI SPDX | sort -u
  SPDX-License-Identifier: LGPL-2.1+
# SPDX-License-Identifier: LGPL-2.1+
# SPDX-License-Identifier: LGPL-2.1-or-later
/* SPDX-License-Identifier: LGPL-2.1+ */
```

**Comment by kennylevinsen** [comment]
It would appear that systemd relicensed most things as LGPL2.1, with a few individual files remaining as GPL2. We initially did have a few of those files, but we seem to have removed them all now.

I think it's fine to remove the GPL2 license file. @emersion, what do you think?

**Comment by emersion** [comment]
If we've removed everything GPL2, this sounds fine.
