### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by emersion** [emersion/basu#6]
Once we've removed all of the Linux-specific stuff, we should look into running this on FreeBSD.

**Comment by kennylevinsen** [comment]
A big question here is what to do with sd_event, which is implemented with epoll and exposed in the sd_bus interface as `sd_bus_(attach|detach|get)_event`.

Maintaining a kqueue implementation in parallel seems like a pain. A portable version implies stripping the sd_event API a bit, which likely drops e.g. sd_event_get_fd, in which case we need to do something new to allow nested event loops.

**Comment by emersion** [comment]
We could go with epoll-shim at first.

**Comment by kennylevinsen** [comment]
Closed by https://github.com/emersion/basu/pull/32.
